[tool.poetry]
name = "minimal-provider-agent-market"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.custom]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
httpx = "0.27.2"
loguru = "^0.7.3"
pydantic = "2.10.3"
pydantic-settings = "^2.7.1"
pre-commit = "^4.0.1"
pygithub = "^2.5.0"
python-dotenv = "^1.0.1"
ruff = "^0.8.4"

[tool.poetry.group.open-hands]
optional = true

[tool.poetry.group.open-hands.dependencies]
python = ">=3.12,<4.0"
openhands-ai = "^0.17.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api" 